# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d65f00b9b89d700cc44d39bfb586d801e4ae0894caaf1ea86da30b6f14bb10ee158fbc20a93eb635beb5629a4d0ab0bc4ffeb7c9aaaea572399ffb97be4b09

test:
  secret_key_base: c2888bd09cb0e9fb7e6d8ee7a2f095d7b2154bc8c6cca6952d608364381b731323e16356355be680214fad60a4677e3254888346d8854498816cec202980342d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
